### ISSUE TITLE
Key Vault URL and  Credential ID are removed after a server restart ( jenkins master running via docker )

### ISSUE THREAD

**Issue by thcp** [jenkinsci/office-365-connector-plugin#112]
First of all thanks for this plugin, its really handy :+1: 

Second, I have been observing a weird behavior regarding the removal of the url and associated credentials from the Configuration page after  a container restart. Currently, was this behaviour experienced before ?

 I'm using  Jenkins v2.150.3

**Comment by damianszczepanik** [comment]
I don't know what are you talking about - more details please

**Comment by thcp** [comment]
For example,

currently  I have defined:

![image](https://user-images.githubusercontent.com/31625914/56068580-4a446b00-5d77-11e9-8e38-fe4d9674e911.png)

Then I restart the server via http://jenkins.somewhere/restart

and right after the server is up:

![image](https://user-images.githubusercontent.com/31625914/56068701-ae672f00-5d77-11e9-8ff1-6dc6c2920855.png)

**Comment by damianszczepanik** [comment]
And how this is related to this plugin?

**Comment by thcp** [comment]
totally my mistake, thats why we should rest more at night.

Have a nice weekend!
