### ISSUE TITLE
Notification on Input Step

### ISSUE THREAD

**Issue by Rocketeer007** [jenkinsci/office-365-connector-plugin#135]
Would it be feasible to add a notification when the Build requests input through an [Input Step](https://wiki.jenkins.io/display/JENKINS/Pipeline+Input+Step+Plugin) in a Pipeline?

In an ideal world, this notification would include both the "Proceed" and "Abort" buttons that are used with a simple input step.  However, since there may be use cases which have parameterised input steps, this may be problematic.

As a simple solution, replacing the default "View Build" button with a "Provide Input" button would be sufficient - that button should link to `${env.BUILD_URL}/input/` so the user can go directly to the input page.

**Comment by damianszczepanik** [comment]
Looks like interesting feature. I have no experiences with Input Step but if you like to prepare pull request for that I will help you and merge it

**Comment by damianszczepanik** [comment]
Should help https://github.com/jenkinsci/office-365-connector-plugin#pipeline-step
