### ISSUE TITLE
Broken multi-branch pipelines

### ISSUE THREAD

**Issue by michelzanini** [jenkinsci/office-365-connector-plugin#142]
After https://github.com/jenkinsci/office-365-connector-plugin/pull/134 we now only get the branch name on the title message for Multi Branch pipelines:

<img width="848" alt="Screen Shot 2019-06-24 at 10 50 31" src="https://user-images.githubusercontent.com/4479787/60010818-7aaa5e80-9670-11e9-8e95-a10a78c26c87.png">

We need to get the job name in as well, otherwise the message is useless.
I don't think we should remove folder names from there - maybe that should be configurable if someone does not want it they can switch a flag or something?

**Comment by damianszczepanik** [comment]
This displayed name of the job. Not branch name.

**Comment by michelzanini** [comment]
Not really, my job has another name.
On multi-branch pipelines there are sub jobs as branches - but people dont
want to see the branch name in the message. This would be useless.

**Comment by damianszczepanik** [comment]
@michelzanini agree, problem is fixed and released now
