### ISSUE TITLE
"Developers" attribute on card is not deduplicated

### ISSUE THREAD

**Issue by soundstripe** [jenkinsci/office-365-connector-plugin#151]
I just ran a job manually from Jenkins, which has the Office 365 Connector enabled upon job completion.

The job finished and the card has a "Developers" attribute that says my name approximately 50 times (I didn't count!). I think it might be the number of SCM commits since the last job run. Anyway... its rather annoying and I wondered if this section could be easily deduplicated.

**Comment by damianszczepanik** [comment]
Already fixed, not released https://github.com/jenkinsci/office-365-connector-plugin/pull/144
