### ISSUE TITLE
Option to view detailed card (old card view) in Teams?

### ISSUE THREAD

**Issue by Wolfe1** [jenkinsci/office-365-connector-plugin#152]
Are there any plans to allow users to view the old detailed teams notification card? The new compact message doesn't deliver the amount of detail we would like. Specifically the information about the total number of tests, how many passed, and how many failed.

Thanks,

**Comment by damianszczepanik** [comment]
You will be probably able to restore this by custom message. I've decided to hide information which are very detailed and valuable only for very specific users.
