### ISSUE TITLE
Hyphens appearing as '\-' in Teams notifications

### ISSUE THREAD

**Issue by danielbecroft** [jenkinsci/office-365-connector-plugin#172]
We have lots of jobs with a hyphen in the name, ie `project-trunk`, etc. When the notification comes through to Teams, the '-' is now appearing with a backslash in front of it `project\-trunk`. 

Note that this only shows up in the Notifications section - the card in the Teams Chat appears correctly. 

Running v4.11.0, Jenkins 2.187

**Comment by damianszczepanik** [comment]
That was improvement about it recently. Attach the screen shot for reference

**Comment by danielbecroft** [comment]
Sorry, the images are below:

![image](https://user-images.githubusercontent.com/8303748/63825101-bcbb8d80-c99c-11e9-80c1-05f959781ecd.png)

![image](https://user-images.githubusercontent.com/8303748/63825112-c644f580-c99c-11e9-9809-593ad1eda932.png)

**Comment by damianszczepanik** [comment]
OK, so it works for MS Teams and that is how was it tested and what was the intention. Where does the first image come from?

**Comment by danielbecroft** [comment]
The first image came from the "Activity" (Feed) panel in Teams. On the left, there's a bell icon. The second image is coming from the Teams channel message itself.
