### ISSUE TITLE
'Back to normal' notification doesn't fire for Unstable > Normal

### ISSUE THREAD

**Issue by danielbecroft** [jenkinsci/office-365-connector-plugin#173]
When a job status moves from Unstable to Normal, no notification is being received, even if the "Back to Normal" option is selected.

**Comment by damianszczepanik** [comment]
Does it look like regression or it was never working as you expect?

**Comment by danielbecroft** [comment]
I remember seeing it before, and I've had some instances of it since raising this issue. It looks to be an intermittent problem rather than a core defect. Strange.

**Comment by damianszczepanik** [comment]
![backtonormal](https://user-images.githubusercontent.com/9612911/69834618-cb377080-123b-11ea-8bd8-c118f36e7d06.png)
works for me
