### ISSUE TITLE
how to send some of Jenkins builds' parameter to Teams

### ISSUE THREAD

**Issue by garumaru** [jenkinsci/office-365-connector-plugin#177]
Hi There,

When Jenkins send notice to Teams, it will contain below items:

Status | Build Success
Remarks | Started by user xxx.

For notification sent to Hipchat or Slack, I can send some of Jenkins builds' parameter as well, but looks like I cannot do the same in O365 plugin?

**Comment by damianszczepanik** [comment]
Looks like #169

**Comment by peetereczek** [comment]
Ok, but what's the status of that development? I can't see that functionality yet on my Jenkins, is there anything to do more with that feature?

**Comment by damianszczepanik** [comment]
It's released
