### ISSUE TITLE
Mention the developer at MS Teams

### ISSUE THREAD

**Issue by peetereczek** [jenkinsci/office-365-connector-plugin#179]
Hi,

I like that there is developer nickname from GIT (even name when same user is on Jenkins)
![image](https://user-images.githubusercontent.com/42431204/65430350-11292000-de18-11e9-831a-1079f1d3cbc0.png)

But is it possible to mention them with '@' to raise a popup on their devices that their code has been build? What we did to have build feed on seperated channel, but not all developers are interested in every build. IMHO this would be nice feature to optionally mention nickname from GIT

**Comment by damianszczepanik** [comment]
Agree, this is great idea but to make it happen you need to contact Microsoft as this is not possible to 'ping' someone
