### ISSUE TITLE
Duplicate fields with 2 or more webhooks in the same job

### ISSUE THREAD

**Issue by angystardust** [jenkinsci/office-365-connector-plugin#180]
I have a job with 2 notification webhooks for 2 different channels belonging to 2 different teams.
This is what i get on the second channel:
![Screenshot from 2019-11-08 16-29-53](https://user-images.githubusercontent.com/1568397/68489809-1a474280-0248-11ea-9401-39c213525043.png)

As you can see, all the fields are duplicated.

**Comment by damianszczepanik** [comment]
If this happens only for second channel it looks like the facts are not cleared properly. Based on the implementation I have no idea how this could happen and also I was not able to confirm it.
I need more details to confirm it or ideally pipeline configuration which I can reuse

**Comment by angystardust** [comment]
Yes @damianszczepanik I can confirm you that it happens only for the second channel configured in the pipeline.
The pipeline is very very simple with just one step using the “ansible” plugin.
I think that if should be quite easy to reproduce.
Let me know if you need further details
Thanks for your time

**Comment by damianszczepanik** [comment]
Share the pipeline so I can try to reproduce it

**Comment by soulus13** [comment]
Hello @damianszczepanik! 
I have been having the same problem, and I think i might have a clue about what is happening here.  

The duplication seems to come from Office365ConnectorWebhookNotifier class, where CardBuilder is injected into a constructor, and CardBuilder, where FactsBuilder is injected into a constructor as well.

When Office365ConnectorWebhookNotifier iterates over the webhooks - same CardBuilder instance is being used (along with the same FactsBuilder instance), thus newly created cards for each subsequent webhook preserve some data (like facts from the builder and potential action) from the previous webhooks. And that results in the data being multiplicated for any webhook apart from the first one, on condition that they react to the same events.

I really hope that this could be helpful, as i really like this plugin, and you have done a great work developing it!

**Comment by damianszczepanik** [comment]
@soulus13 Good job, I've confirmed your assumption and fixed the problem. Will write some tests and publish new release

**Comment by angystardust** [comment]
Thanks a lot @damianszczepanik and @soulus13!
