### ISSUE TITLE
Not possible to mention people in jenkins notification message

### ISSUE THREAD

**Issue by sruthicps** [jenkinsci/office-365-connector-plugin#181]
Using the following code to send notification message to MS Teams.
`office365ConnectorSend message: 'This is a sample notification', status: currentBuild.result, webhookUrl: "https://outlook.office.com/webhook/24340149-02xxxxxxxxxx"
`
it would be nice if there is an option for mentioning people in notification message. For example '@developers'

**Comment by damianszczepanik** [comment]
Duplicate of #179
