### ISSUE TITLE
Is option "custom message" active?

### ISSUE THREAD

**Issue by matlion** [jenkinsci/office-365-connector-plugin#184]
This pull request describes the option to add a _custom message_: https://github.com/jenkinsci/office-365-connector-plugin/pull/91
I'm using the latest plugin version 4.12.1 of the Office 365 Connector but I can't see an option _custom message_.

Under _Advanced configuration_ I can see _Macros_ and _Fact Definitions_.

I'm using free style projects and pipeline projects with Jenkins 2.176.4

**Comment by damianszczepanik** [comment]
Did you read README file?

https://github.com/jenkinsci/office-365-connector-plugin#pipeline-step

**Comment by matlion** [comment]
Thanks, that helps. So I add the teams integration to the pipeline script.
I just expected an option in the GUI.
