### ISSUE TITLE
Provision to supply activityImage for the messageCard section

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [jenkinsci/office-365-connector-plugin#185]
Request to provide a Provision to supply activityImage for section of the message card. Whenever the pipeline fails, I want to set this image in addition to `themerColor`. Because I couldn't see the theme color in the mobile app. of teams; also having this `activityImage`,  it's apparent to the user that build is failed or successful. Some Images like `Green Tick Mark` for pass and `Red cross Mark` for failure would be good. 

the equivalent JSON like...
"sections": [
    {
      "activityTitle": "test",
      "activitySubtitle": "test sub",
      "activityImage": "'<Image_URL>'",
      "activityText": "something...."
    }

**Comment by damianszczepanik** [comment]
I don't understand what you need and for what

**Comment by Prasannajnaeyulu** [comment]
I mean, I am using this connector to post jenkins build result to microsoft teams. I want to customize the message that is sending by this **Office365Connector** plugin. 

This is what it is sending..
![image](https://user-images.githubusercontent.com/2508680/71241638-05100a00-2304-11ea-9687-3504117b6a09.png)

Is there anyway I can customize this message? I want to include some image like Green tick mark to the left if the build is successful and red cross mark on failure.

**Comment by damianszczepanik** [comment]
Answer is available on main page of this plugin
