### ISSUE TITLE
Build Configuration Page Organization

### ISSUE THREAD

**Issue by JosephWitthuhnTR** [jenkinsci/office-365-connector-plugin#188]
After installing this plug-in, the header makes it look like options are related to Office 365 Connector even when they are not, including options like build parameters and the JDK setting.

See this screenshot:
![image](https://user-images.githubusercontent.com/28634003/72622977-e3597100-3909-11ea-8e24-ed8d6f823075.png)

This doesn't have any functional harm, but the look and feel is "off".

**Comment by damianszczepanik** [comment]
If you check carefully you can see that the background is different. This is how Jenkins presents options but if you have idea how to improve it I'd would be happy to accept this PR
