### ISSUE TITLE
Include build failure message

### ISSUE THREAD

**Issue by HitoTech** [jenkinsci/office-365-connector-plugin#189]
Hello,

I'm currently trying to migrate my Jenkins notifications from Slack to Microsoft Teams, and I had no problem so far with this plugin.

But in Slack, when I had an error on a build, I would receive a notification with the build failure message like this :

![image](https://user-images.githubusercontent.com/3921746/73060290-cab40280-3e97-11ea-8cdf-058ed97500fc.png)

Unfortunately, this is what I get on Teams : 

![image](https://user-images.githubusercontent.com/3921746/73060460-2a121280-3e98-11ea-9ae3-e90cb1e036b1.png)

Is there a way to add the error message in a custom fact, redesign it, or is there something that I'm missing ?

Anyway, thank you for this plugin !

**Comment by damianszczepanik** [comment]
Check README file where you have example how to fully customize message which is send to MS Teams
