### ISSUE TITLE
Advice request: how to implement option to use green color for SUCCESS builds

### ISSUE THREAD

**Issue by ljader** [jenkinsci/office-365-connector-plugin#192]
Hi @damianszczepanik (and anyone who wants to paticipate)
I want to implement ability to use green color for notification from successful build and I ask for your opinion how.

Green is more "natural" for Jenkins-unaware folks, e.g. analysts, testers, sales people - so notifications from this plugin would be more readable also for "non-build" pipelines.

**Possible implementations**
1. Simplest - add checkbox to "Use green color for Success result"
2. Still simple - add checkbox to "Override color for Success result", which shows Input to specify the color
3. Advanced - implement "Jenkins extenstions" which modify the behavior of the plugin - like with Git Plugin you can select additional behavior like "Use shallow clone"

Thanks in advance any feedback.

**Comment by damianszczepanik** [comment]
I'm OK to change it without customization so green will be used by default. Can you prepare PR for that?
