### ISSUE TITLE
[bug] webhooks urls are ignored if a URL is defined in Job Notification section of the configuration of the job

### ISSUE THREAD

**Issue by n0rig** [jenkinsci/office-365-connector-plugin#194]
Currently on version 4.12.2 of the plugin.

**What is the bug?**
Step 3 below is not respected and the message is **ALWAYS** sent to the url defined in the pipeline Job's Notification section.

**Steps to reproduce:**
1. Create a new pipeline job.
2. Define a webhook URL inside the Job Notification section of the configuration of the job. Here is the screenshot for that section:
  
![image](https://user-images.githubusercontent.com/1235638/74283780-7ced2600-4cf0-11ea-9404-0fb2613bb257.png)

3. Inside your jenkinsfile, use the following command to send to **A DIFFERENT** webhook url.
```groovy
office365ConnectorSend message: "<Your message>", status:"<Build status>", webhookUrl:'<A DIFFERENT URL THAN IN THE CONFIGURATION>'
```

**Comment by damianszczepanik** [comment]
@n0rig very good report for very old issue - looks like nobody uses two uri for single hook. Thanks!

**Comment by jjathman** [comment]
Do you know when the next patch release will be? We actually just ran in to this same issue.

**Comment by n0rig** [comment]
@damianszczepanik; Thank you for the fix!
