### ISSUE TITLE
Not able to see test automation results in Microsoft teams via jenkins

### ISSUE THREAD

**Issue by Wajeed-msft** [jenkinsci/office-365-connector-plugin#195]
Hi Team, 

Could you please help to confirm if following is a valid ask?
https://stackoverflow.com/questions/59729619/not-able-to-see-test-automation-results-in-microsoft-teams-via-jenkins

**Comment by ljader** [comment]
It's been removed in pull #116

**Comment by damianszczepanik** [comment]
True

**Comment by jacobweber** [comment]
Could it be added back in some form? The Slack plugin has this, and it's very useful. Maybe the values could be passed as environment variables, so they could be printed in custom Facts?

**Comment by Adityanr** [comment]
Yes could it be added back? My organisation also needs it.

**Comment by damianszczepanik** [comment]
It was removed on user's request

**Comment by amai2012** [comment]
I also miss the additional information.
People could avoid many mouse clicks to retrieve facts from Jenkikns ui if some more information would be posted in teams.
