### ISSUE TITLE
Actionable buttons within notifications

### ISSUE THREAD

**Issue by KevinM2k** [jenkinsci/office-365-connector-plugin#197]
Hi,

In the description of the plugin it states:

"Plugin is used to send actionable messages in Outlook, Office 365 Groups, and Microsoft Teams."

However although I can send messages without any issues, sending actionable messages (with buttons and interaction) doesn't seem possible.

Am I missing some documentation or is this something that isn't available just yet?

Thanks
Kevin

**Comment by damianszczepanik** [comment]
If you configure plugin with eg git repository you can have some buttons like https://github.com/jenkinsci/office-365-connector-plugin#with-jenkins-plugin

**Comment by KevinM2k** [comment]
Hi,

I'm trying to use the potentialAction methods to set up custom buttons, it is in the code base but there is no documentation on how it works.

Also how do I turn off the automatic buttons that appear such as 'View Pull Request', 'View Build', and the extra information such as 'Pull Request Title' and 'Pull Request Author'. I wan't to have full control over the info that goes in to teams.

Thanks
Kevin

**Comment by damianszczepanik** [comment]
Well, I haven't tried to do that so I'm not sure if this works and how. You can test it and let me know later or prepare PR with support for that great option

**Comment by GuillaumeExia** [comment]
> If you configure plugin with eg git repository you can have some buttons like https://github.com/jenkinsci/office-365-connector-plugin#with-jenkins-plugin

Hi @damianszczepanik, could you please elaborate on how to "configure plugin with eg git repository". I am trying to achieve this in a Jenkins Pipeline, but I am not able to understand what needs to be configured. Thank you.
