### ISSUE TITLE
Can you add support for user Chat notification?

### ISSUE THREAD

**Issue by igreenfield** [jenkinsci/office-365-connector-plugin#198]
From that [Link](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-a-chat) it seems it can be done. and very use full for sending a notification to the man that breaks the Jenkins build

**Comment by damianszczepanik** [comment]
Nice, did you try with https://github.com/jenkinsci/office-365-connector-plugin#pipeline-step ?
