### ISSUE TITLE
Can you add support for custom activityTitle

### ISSUE THREAD

**Issue by redi-tjandr** [jenkinsci/office-365-connector-plugin#200]
I have a generic notification job, so I'd like to override the title with the calling job's name so it's more obvious what failed. If you can make activityTitle a parameter I can pass in to the office365ConnectorSend that would solve the problem.

**Comment by damianszczepanik** [comment]
What I can suggest is to use https://github.com/jenkinsci/office-365-connector-plugin#pipeline-step
I don't have plan for custom activity title
