### ISSUE TITLE
Plugin does not use final env variable values in fact evaluation

### ISSUE THREAD

**Issue by teohaik** [jenkinsci/office-365-connector-plugin#203]
Hello all,
great work in this plugin.

However, I face a problem in my setup. 
I use the plugin in a deployment script and i want to notify the team about which modules have been deployed, so I inserted some facts:

![image](https://user-images.githubusercontent.com/1785012/79312778-0e9f2c80-7f08-11ea-96b5-7c10cc1bfe4b.png)

The variables have been initialized here:

![image](https://user-images.githubusercontent.com/1785012/79312922-4c9c5080-7f08-11ea-86c5-1db1c9b1a275.png)

In the deployment script I update the variables:

![image](https://user-images.githubusercontent.com/1785012/79312834-237bc000-7f08-11ea-9601-69b74758ce0d.png)

But the team, gets only the initial values in the message:
![image](https://user-images.githubusercontent.com/1785012/79312991-5f168a00-7f08-11ea-8b81-1c761e492a71.png)

What is going wrong?

**Comment by damianszczepanik** [comment]
IMO it updates variable locally like for every shell
