### ISSUE TITLE
"View Build" button actually use the ${RUN_DISPLAY_URL} Jenkins environment variable

### ISSUE THREAD

**Issue by kayhiangtan** [jenkinsci/office-365-connector-plugin#204]
The "View Build" button actually use the ${RUN_DISPLAY_URL} Jenkins Environment Variable, whereas normally should use ${BUILD_URL} instead. Anyway to override ${RUN_DISPLAY_URL} with ${BUILD_URL} using the plug-in alone?

**Comment by damianszczepanik** [comment]
This is feature, not a bug
