### ISSUE TITLE
What is the best way to modify all my jobs with this connector?

### ISSUE THREAD

**Issue by CRuD117** [jenkinsci/office-365-connector-plugin#205]
I have a customer who is moving from HipChat notifications to Teams notifications.  They have thousands of jobs to update.  What is the best way to globally inject this connector to Teams for everything?

**Comment by damianszczepanik** [comment]
It's rather question to Jenkins leaders than to plugin author

**Comment by TobiX** [comment]
I'd suggest the following tools (from best to worst):
1. The [JobDSL](https://github.com/jenkinsci/job-dsl-plugin/wiki) plugin
2. Write an extension for [Configuration Slicing](https://plugins.jenkins.io/configurationslicing/)
3. Using groovy scripting inside Jenkins to change the config of all jobs
4. Edit the job XML directly
