### ISSUE TITLE
Unable to configure office365connector plugin using DSL configure for flow-definition 

### ISSUE THREAD

**Issue by Aaqib041** [jenkinsci/office-365-connector-plugin#206]
Hi ,

I am creating jenkins jobs using DSL , so as part of it I want to configure office365connector plugin.
I tried to follow documentation which shows configure example , but I am creating pipeline jobs using DSL , so xml generated is flow-definition type and configure block is not working for same . I am sharing the code snippet and error below . Kindly check and help.

**Code Snippet :**

projects.collect { app ->
  
    app.services.collect { job ->
           
        println "${job.name}"
        pipelineJob("${app.project}/${job.name}-dev") {
            configure { 'flow-definition' ->
                        flow-definition / 'properties' << 'jenkins.plugins.office365connector.WebhookJobProperty' {
                        webhooks {
                            'jenkins.plugins.office365connector.Webhook' {
                                name("${job.name}-notify")
                                url('https://outlook.office.com/webhook/ea7992fc28e-b5c4-58ad7')
                                startNotification(false)
                                notifySuccess(true)
                                notifyAborted(false)
                                notifyNotBuilt(false)
                                notifyUnstable(true)
                                notifyFailure(true)
                                notifyBackToNormal(true)
                                notifyRepeatedFailure(false)
                                timeout(30000)
                                macros(class: 'empty-list')
                                factDefinitions(class: 'empty-list')
                            }
                        }
                    }
                }
            definition {
                logRotator {
                    artifactDaysToKeep(30)
                    artifactNumToKeep(10)
                    daysToKeep(30)
                    numToKeep(10)
                }
                triggers {
                    pollSCM {
                        scmpoll_spec("")
                        ignorePostCommitHooks(false)
                    }   
                }
                throttleConcurrentBuilds {
                    throttleDisabled(true)
                }
           }
        }
    }
}

**Error :** 

ERROR: startup failed:
devBuild.groovy: 18: expecting '}', found '->' @ line 18, column 43.
   configure { 'flow-definition' ->
                                 ^

1 error

**XML File :** 

XML starts with 

<flow-definition plugin="workflow-job@2.35">
	<actions>

**Comment by damianszczepanik** [comment]
I don't have experience with this but based on the error this is problem with syntax, not

**Comment by SivaVasipalli** [comment]
@Aaqib041  i was able to get this with small change below 

 configure { project ->
                    project / 'properties' << 'jenkins.plugins.office365connector.WebhookJobProperty' {
                    webhooks {
                        'jenkins.plugins.office365connector.Webhook' {
                            name("${job.name}-notify")
                            url('https://outlook.office.com/webhook/ea7992fc28e-b5c4-58ad7')
                            startNotification(false)
                            notifySuccess(true)
                            notifyAborted(false)
                            notifyNotBuilt(false)
                            notifyUnstable(true)
                            notifyFailure(true)
                            notifyBackToNormal(true)
                            notifyRepeatedFailure(false)
                            timeout(30000)
                            macros(class: 'empty-list')
                            factDefinitions(class: 'empty-list')
                        }
                    }
                }
            }

**Comment by damianszczepanik** [comment]
Worth to update README file? Can you prepare PR with that ?
