### ISSUE TITLE
More customization?

### ISSUE THREAD

**Issue by TobiX** [jenkinsci/office-365-connector-plugin#207]
I'd like to customize the sent messages a bit more. I'm fine with implementing the changes myself (might take some time ;)) and sending a pull request later. I'd just like to know how you'd like the extension:

1. Suppressing the status? I'm sending messages from some jobs which don't relate to the overall build status, so the extra "Status: Running" line is only a distraction. Should I add a new option (`showStatus` with default `true` or `suppressStatus` with default `false`) or somehow integrate it into the existing option (which doesn't seems appealing to me - `status: null` is already special, `status: 'NONE'` just looks strange)
2. Suppressing or customizing the header? Again, the channel into which I'm posting isn't interested in which job is posting the notification, only the notification itself. I would probably make it analogous to the `status`, so users are able to overwrite the header (`header: 'My notification'`) and use another parameter to totally hide it (`showHeader` or `suppressHeader`)
3. Actions: Make the `ActionableBuilder` configurable: Add a new option `actions`, which takes an array of "potential actions", the current behaviour would map to `actions: [pullRequestLink(), buildLink()]`, a user could than specify `actions: []` to disable all links or customize the order - later, new actions can be implemented: `actions: [buildLink(), customLink('Google', 'https://www.google.com')]`

WDYT?

**Comment by damianszczepanik** [comment]
In the past I have removed items from messages which were not very popular.
Message is some kind of notification and I'm not going to add some specific information - for this you can add action which transfers you to browser where you can check details.
Pull requests are available but if you find that this is not as good as expected let me know
