### ISSUE TITLE
Jenkins logo in teams looks streched/blurry

### ISSUE THREAD

**Issue by movedoa** [jenkinsci/office-365-connector-plugin#217]
A bit of a nitpick but the jenkins logo in teams looks blurry and seems to be streched out.

![grafik](https://user-images.githubusercontent.com/13309951/83165507-e95c2b80-a10d-11ea-9397-3a0dc55ec0ec.png)

For comparison, this is how the logo should look like:
![grafik](https://user-images.githubusercontent.com/13309951/83165733-41932d80-a10e-11ea-91ee-70d438b0bb3f.png)

**Comment by damianszczepanik** [comment]
Where does it come from?

**Comment by dcendents** [comment]
AFAIK this is set on the microsoft side of things when the webhook is created, I used a different log and mine looks fine.

See https://www.jenkins.io/artwork/ for nice jenkins logos.

**Comment by damianszczepanik** [comment]
true
