### ISSUE TITLE
How can I use macros in DSL?

### ISSUE THREAD

**Issue by Muji86** [jenkinsci/office-365-connector-plugin#221]
Hi,

I have not found any example of how I can utilise `macros` in my DSL. I didn't find the [Token Macro site](https://github.com/jenkinsci/token-macro-plugin) particularly helpful for what I need

What I'm trying to acheive is a check that the branch is `master` so notifications aren't sent for all branches

Any help will be much appreciated.

**Comment by damianszczepanik** [comment]
I will update readme file. In meantime you can check similar approach https://github.com/jenkinsci/build-history-manager-plugin#remove-builds-based-on-a-parameter
