### ISSUE TITLE
Message character limit

### ISSUE THREAD

**Issue by VibinD** [jenkinsci/office-365-connector-plugin#225]
I am trying to use the following and it trim the message after 365 character. I am sending a link in the message which has 600 characters on it. Are you restricting any limit

office365ConnectorSend webhookUrl: 'teams_channel_url',
     message: "message body value with link which has 600 character(s)",
     status: 'Success',
     color: '#0000FF'

**Comment by damianszczepanik** [comment]
No, probably office365 limitation, check with documentation if any
