### ISSUE TITLE
Allow to disable Markdown in message text

### ISSUE THREAD

**Issue by TheSlowGrowth** [jenkinsci/office-365-connector-plugin#228]
The message 
```
office365ConnectorSend message: "<pre> my _message_ with _underscores_", webhookUrl: "<URL>"
```
will result in the following formatting:

>  my _message_ with _underscores_

This is problematic for us - we publish the name of failed tests in the message and some tests contain underscores which must not be treated as markdown. AFAIK there is no way to disable this formatting.

It would be very helpful if there was another option to disable markdown entirely like this:
```
office365ConnectorSend message: "<pre> my _message_ with _underscores_", webhookUrl: "<URL>, markdown: false "
```

This may be related to #82 where the same was already fixed for the header of the message

**Comment by damianszczepanik** [comment]
This is more like feature. Try to escape underscore char to make it work the way you like

**Comment by zett42** [comment]
It works, you are just missing the closing _pre_ tag:

`office365ConnectorSend message: "<pre> my _message_ with _underscores_</pre>", webhookUrl: "<URL>"`

Alternatively to _pre_, you can enclose message in backticks, which will be formatted slightly differently.

**Comment by TheSlowGrowth** [comment]
Sorry, the closing _pre_ was there, I had missed it when writing the issue.
Thanks for the suggestion with the backticks. That worked just fine!
