### ISSUE TITLE
Repeated Teams notifications for a single office365ConnectorSend() step invocation

### ISSUE THREAD

**Issue by ml019** [jenkinsci/office-365-connector-plugin#233]
I have a single invocation of the office365 step in a Jenkinsfile as follows;
```
                office365ConnectorSend (
                    message: "**${title}** | ${BUILD_DISPLAY_NAME}  \n${message}",
                    webhookUrl: channel,
                    color: colour
                )
```

We are running Jenkins 2.235.5 with plugin version 4.13.2,

In Teams, I receive three identical notifications. I have checked and there is only one instance of the connector configured in Teams.

Wondering if it is because I am not providing a status value? It looks like status is something I can optionally provide but I couldn't find more explicit information in the documentation on the accepted values. 

Alternatively is the status parameter provided so I can control the status changes that trigger the sending of the notification? If so, what are the accepted values?

**Comment by damianszczepanik** [comment]
Add some debug message to confirm if this block is invoked three times or only one. Check sample configuration from plugin page to eliminate your concern about missing status value.

**Comment by ml019** [comment]
Builds logs show one invocation.

I tried adding an extra logger for jenkins.plugins.office365connector to check for multiple invocations but got no trace. By the looks of the code, it only logs webhook delivery failures - the logging of attempts is commented out.

By the looks of https://github.com/jenkinsci/office-365-connector-plugin/blob/f0aea135e001cf06ba529b1510785358ceeab760/src/main/java/jenkins/plugins/office365connector/Office365ConnectorWebhookNotifier.java#L99, because I am setting the message, the status is ignored in constructing the message, so that's not likely to be the culprit.

Is there any way the `onStarted` and `onCompleted` build listeners from https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/workflow/Office365ConnectorBuildListener.java could be firing as well as the step notification?

**Comment by damianszczepanik** [comment]
I need some more information which allow me to identify the problem:
- does it happen for notification configured according to readme file?
- does it happen for other notification for this build and this Teams channel?


missing status should not be a problem

**Comment by ml019** [comment]
The only thing I am not currently doing is to set the status, based on example on the plugin page 

"
To send message from inside Jenkinsfile:

In the script use the following command:
office365ConnectorSend message: "<Your message>", status:"<Build status>", webhookUrl:'<The connector webhook url>'
"

I added a status parameter and it is now included in the notification. However I still received three identical notifications for one step invocation.

I am using the same mechanism to send from multiple Jenkinsfile jobs to multiple Teams channels and see the same behaviour across jobs and channels.

**Comment by ml019** [comment]
Latest example showing Status field

![duplicatenotifications](https://user-images.githubusercontent.com/5861038/95004838-43c94380-063c-11eb-92fe-d0c92d18e27e.png)

**Comment by damianszczepanik** [comment]
This produces only single message:

```
pipeline {
    agent any
    stages {
        stage('Exit code') {
            steps {
                office365ConnectorSend message: "Damian", status:"", webhookUrl: "https://outlook.office.com/webhook/..."
            }
        }
    }
}

```

**Comment by orovp** [comment]
On HttpWorker class exist a retry logic for http calls with default value to 3. When call is different than 200, code logic will retry three times the call. Is it possible that exist some situation on destination server that send a code response different than 200 and message is properly delivered on teams channel?

**Comment by ml019** [comment]
That would align with what I am seeing. Is there anything I can log in Jenkins to observe the retries?

**Comment by damianszczepanik** [comment]
Since this is the first such request I believe for all other this retries mechanism works as expected. Then my advice is to check what is going on between Jenkins and server where hooks are sent.
You can try to generate new hook to check if it helps

**Comment by ml019** [comment]
I don't control the receiving system - MS does. Hence my only option is to log at the Jenkins end.
