### ISSUE TITLE
DisplayName Configure in DSL pipeline Jenkins

### ISSUE THREAD

**Issue by alfador1** [jenkinsci/office-365-connector-plugin#235]
Hello,

My question is the follow:

When configuration the card at the top it says "Message from...." >> https://raw.githubusercontent.com/jenkinsci/office-365-connector-plugin/master/.README/webhook.png
Can this part be configured?
I see options: message, status, color, webhookURL, BUT I don't see anything to change the display name on the top?
Can that happen?

**Comment by damianszczepanik** [comment]
No. However you can change the hook and use the one dedicated for Jenkins. Check readme page https://github.com/jenkinsci/office-365-connector-plugin
