### ISSUE TITLE
Adding committers/culprits to factdefinitions when using Jenkinsfile

### ISSUE THREAD

**Issue by fergzie** [jenkinsci/office-365-connector-plugin#239]
When using the Plugin via GUI it adds committers/culprits to the factsdefinitions, but is there a way to add this to a Jenkinsfile when using the office365ConnectorSend call ?

If so, what would I write in the "template" field in factDefinitions?

**Comment by damianszczepanik** [comment]
Are you having the most recent version? AFAIR such problem was in the past

**Comment by fergzie** [comment]
I'm using the latest version.
The problem is that there is no example on how this is done in a Jenkinsfile. 

What would I write in the factdefinitions to add committers/culprits, when using pipeline?

`office365ConnectorSend webhookUrl: "URL", factDefinitions: [[name: "Culprit", template: "what to write here??"]]`

**Comment by damianszczepanik** [comment]
OK, attach screenshots for reference so this can be handled

**Comment by fergzie** [comment]
![Capture](https://user-images.githubusercontent.com/38907264/105627417-c3497100-5deb-11eb-83a2-6cf9e07b715e.PNG)

What do I write here in order to get culprits shown in Teams as shown below?

![teams_connector](https://user-images.githubusercontent.com/38907264/105627631-d90b6600-5dec-11eb-8ce9-92de95fe3b28.PNG)

**Comment by damianszczepanik** [comment]
This is not matter of gui or pipeline but father fact if SCM changes are detected or not

**Comment by fergzie** [comment]
Ok, so if there is nothing that I need to do to make the plugin show SCM changes (culprits) in Microsoft teams notification, then I can say that it doesn't work. 

I'm using version 4.13.2.

**Comment by damianszczepanik** [comment]
Jenkins delivers information about SCM changes and the plugin uses this data. As I remember when particular build shows changes then notification has such information and it adds into the message

**Comment by fergzie** [comment]
As I said i'm my previous post, then this behavior does NOT work and therefore this is an issue, that should be fixed.

**Comment by damianszczepanik** [comment]
I don't think this is a plugin issue and that's why I closed this.

**Comment by schaudhary111** [comment]
@fergzie Did it work for you ?? I am also facing similar issue. What is template here ? 

`office365ConnectorSend webhookUrl: "URL", factDefinitions: [[name: "Culprit", template: "**what to write here??**"]]`
