### ISSUE TITLE
Your connector is running on old configuration

### ISSUE THREAD

**Issue by ngcdev** [jenkinsci/office-365-connector-plugin#240]
Hello,

We've been using the office-365 connector for several months sending messages to a Teams channel this way from a pipeline:

```
office365ConnectorSend  status: 'Build Fixed', color: '#66e066', message: "${env.JOB_NAME} ${currentBuild.currentResult} [Open](${env.BUILD_URL})", webhookUrl: 'https://outlook.office.com/webhook/...'
```
A day or so ago, the message is being posted with this additional message:

> Important: Your connector is running on old configuration. Navigate to connector configuration window to update to new configuration.

Not sure where this is coming from and what are we supposed to update.

Any help will be appreciated.

Thanks!

**Comment by damianszczepanik** [comment]
This is true. Configuration has changed long time ago but both were supported. Where have you seen such message? I have just generated new message and looks fine on Teams

Anyway I'm looking someone who would like to rewrite code to fit new configuration...

**Comment by Thieum** [comment]
I think it's linked to this change on office365 side: https://admin.microsoft.com/AdminPortal/Home?#/MessageCenter/:/messages/MC234048

The connector webhook URL needs to be updated through teams and changed where it is used.

Not sure it implies any changes on the side of the plugin.

**Comment by redsoft7** [comment]
With the new URL I no longer receive notifications on Teams.

From the logs there are no errors:
`[Office365connector] Matched status 'SUCCESS' for webhook with name 'null'.`

**Comment by redsoft7** [comment]
This is the error in the log file:
```
Mar 05, 2021 9:37:31 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
I/O exception (javax.net.ssl.SSLException) caught when processing request: hostname in certificate didn't match: <steenergy.webhook.office.com> != </*.clo.footprintdns.com/*.hotmail.com/*.internal.outlook.com/*.live.com/*.nrb.footprintdns.com/*.office.com/*.office365.com/*.outlook.com/*.outlook.office365.com/attachment.outlook.live.net/attachment.outlook.office.net/attachment.outlook.officeppe.net/attachments.office.net/attachments-sdf.office.net/ccs.login.microsoftonline.com/ccs-sdf.login.microsoftonline.com/hotmail.com/mail.services.live.com/office365.com/outlook.com/outlook.office.com/substrate.office.com/substrate-sdf.office.com/outlook.com>
```

**Comment by movedoa** [comment]
> 
> 
> This is the error in the system log file:
> 
> ```
> Mar 05, 2021 9:37:31 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
> I/O exception (javax.net.ssl.SSLException) caught when processing request: hostname in certificate didn't match: <steenergy.webhook.office.com> != </*.clo.footprintdns.com/*.hotmail.com/*.internal.outlook.com/*.live.com/*.nrb.footprintdns.com/*.office.com/*.office365.com/*.outlook.com/*.outlook.office365.com/attachment.outlook.live.net/attachment.outlook.office.net/attachment.outlook.officeppe.net/attachments.office.net/attachments-sdf.office.net/ccs.login.microsoftonline.com/ccs-sdf.login.microsoftonline.com/hotmail.com/mail.services.live.com/office365.com/outlook.com/outlook.office.com/substrate.office.com/substrate-sdf.office.com/outlook.com>
> ```

I have the same issue, teams notifications are no longer working with the new url and i get the SSLException in the logs.

**Comment by movedoa** [comment]
FYI: I managed to fix the ssl error by updating the jdk that jenkins runs with from 1.8.0_101 to 11.0.10.9

**Comment by damianszczepanik** [comment]
@movedoa  thanks for the tip

**Comment by damianszczepanik** [comment]
I found that you need to update or create new hook to fix the problem. Then old Jenkins configuration works fine without above notification.
