### ISSUE TITLE
Appears in the middle of General

### ISSUE THREAD

**Issue by jacobweber** [jenkinsci/office-365-connector-plugin#243]
The heading for this plugin appears right in the middle of the General section. So it looks like the checkboxes below it (e.g. Permission to Copy Artifact) are part of Office 365 Connector, and not General.

Jenkins 2.281

![sample](https://user-images.githubusercontent.com/542988/109579517-e67fd400-7aad-11eb-9952-6b809db13eee.png)

**Comment by damianszczepanik** [comment]
This is not perfect as I don't add extra separator unless Jenkins does not make it happen for every plugin.
If you add Webhook it looks much better
