### ISSUE TITLE
Fact definitions - default values and order

### ISSUE THREAD

**Issue by Giusti** [jenkinsci/office-365-connector-plugin#244]
So I wanted to use Fact definitions to display a deployment notification in our Teams channel

The goal was to display the status of deployment (we have multiple in some builds)
The Person and Team which triggered the deployment
Remove all the default values like Remarks, Developers and so on

I did the following:

```
factDefinitions: [
  [name: "Deployment", template: LAST_STAGE],
  [name: "Status", template: env.D_STATUS],
  [name: "Started By", template: env.PERSON],
  [name: "Developers", template: env.TEAM],
  [name: "Remarks", template: null]
]
```
But I dont know how I am able to remove or override the "default" facts that are shown (Status, Remarks, Commiters, Developers)

![facts](https://user-images.githubusercontent.com/6214919/109667444-6c645380-7b70-11eb-8a6f-2b07b9af9818.png)

Also as you can see in the facts I ordered them like this (1. Deployment, 2. Status, 3. Started By)
And in the picture the order is completly different

Also I could not find any way to change the title of the notfication, for deployments I would rather have "Deployment Dev" for exmaple but this also seems to be fixed I guess

Is there any way or are these values just hardcoded?

**Comment by damianszczepanik** [comment]
You cannot change the order or select which items should be displayed

**Comment by damianszczepanik** [comment]
What might be helpful for you is https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/test/resources/requests/sendstep.json
