### ISSUE TITLE
Feature Request: Compact Teams notifications

### ISSUE THREAD

**Issue by zaneobrien** [jenkinsci/office-365-connector-plugin#250]
### Dependencies

None

### Feature Request

It would be nice to have an option for compact notifications. It looks like someone already [developed this in the past](https://github.com/olegfeferman/office-365-connector-plugin) but it never got merged into the main project. IMO, the current notifications are too large (vertically) and it would be nice to have an option to make them smaller, this would be especially nice for matrix jobs that send 10-20 notifications in a channel.

**Comment by zaneobrien** [comment]
Hey @damianszczepanik what are you thoughts on this?

**Comment by damianszczepanik** [comment]
Happy to accept PR about this but I don't have plan to add support about it by myslef
