### ISSUE TITLE
Icons in message

### ISSUE THREAD

**Issue by AlexBravoInostroza01** [jenkinsci/office-365-connector-plugin#253]
¿Is it possible to add icons to the message?

Similar to slack

![image](https://user-images.githubusercontent.com/77693511/125103964-dc4c9280-e0aa-11eb-986a-efd61eb83c1e.png)

**Comment by damianszczepanik** [comment]
Not supported

**Comment by AlexBravoInostroza01** [comment]
Solved: I had to perform a patch solution

![image](https://user-images.githubusercontent.com/77693511/125131678-1e88ca80-e0d1-11eb-9ebb-597d342c3c0e.png)

![image](https://user-images.githubusercontent.com/77693511/125131698-27799c00-e0d1-11eb-87d9-8d914f981740.png)
