### ISSUE TITLE
Different notification view if message property is added

### ISSUE THREAD

**Issue by shubsaini09** [jenkinsci/office-365-connector-plugin#255]
With no message property

![image](https://user-images.githubusercontent.com/12813253/126643047-27faa33b-6131-4f78-9090-0f486cd4055b.png)

Code

```
office365ConnectorSend status: "SUCCESS", webhookUrl: 'webhookurl'
```

With message property

![image](https://user-images.githubusercontent.com/12813253/126643119-0ec50756-1885-498c-ade2-122e16f461bd.png)

Code

```
office365ConnectorSend message: "my custom message", status: "SUCCESS", webhookUrl: 'webhookurl'
```

Not sure if this is a bug or is this an expected behavior? Can someone please help me achieve all the details as given in image 1 with message property.

**Comment by AlexBravoInostroza01** [comment]
With code apparently it does not take what you are asking, but if you do it in the style without code it will take those settings.

**Comment by damianszczepanik** [comment]
First option does not take a message as the parameter
