### ISSUE TITLE
Use a real link for "View build" button

### ISSUE THREAD

**Issue by Glandos** [jenkinsci/office-365-connector-plugin#263]
### Feature Request

My company forced us to use Teams. However, I must run Teams on a remote Windows, because it is not my development platform. Currently, the "View Build" button is not a link in the message, so I have to click it, wait for the Windows browser to open, then copy the link from the URL bar, and I get the link.

Would it be possible to have a link directly in the message itself?

**Comment by damianszczepanik** [comment]
You can define Jenkins URL during Jenkins setup then you can change Jenkins url to the proper url so your browser will open it with the proper value/dns

**Comment by Glandos** [comment]
The URL is OK. But I would like to have the URL without clicking on the button. I would like to be able to copy/paste the link directly from the message.

**Comment by damianszczepanik** [comment]
Then this is completely new story which needs to be implemented. I don't have plan for this
