### ISSUE TITLE
More compact messages

### ISSUE THREAD

**Issue by Glandos** [jenkinsci/office-365-connector-plugin#264]
### Feature Request
Current notification use a lot of pixels in height, and my screen have much more pixels in width.
Would it possible to think of a compact layout. E.g. merge the title with the subtitle and the Status in one line: `Back to normal for "project" in build #1898`.

Remarks and other fields seems OK, even if I guess that developers can be removed if they are the same as commiters.

**Comment by damianszczepanik** [comment]
This would require lot of refactor and use new layout proposed by Microsoft

**Comment by PeteAudinate** [comment]
The new Teams card layout redesign means there's now no way of seeing if the notification is for a Success or Failure without clicking "see more":

![image](https://github.com/jenkinsci/office-365-connector-plugin/assets/99274874/0f5faef9-0ee6-4642-9388-7a48bb58c8f9)

- Color support has been removed (https://github.com/MicrosoftDocs/msteams-docs/issues/10062#issuecomment-1862178211).
- Cards are now so small that only the title and subtitle are shown.

Adding the build status to the title (or subtitle)field would fix this.

**Comment by Glandos** [comment]
I'm glad to use the old client. But sad to see that Microsoft is always doing the same thing again and again.
