### ISSUE TITLE
Color param not working on `office365ConnectSend` Jenkinsfile DSL invocation

### ISSUE THREAD

**Issue by luke-hill** [jenkinsci/office-365-connector-plugin#276]
### Jenkins and plugins versions report

office365 connector is 4.14.0
jenkins is 2.316

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker in Docker agent

### Reproduction steps

Jenkinsfile with `color` param set. i.e. `color: 'Red'` as outlined in docs.

![image](https://user-images.githubusercontent.com/20105237/174030093-bc42155f-bcb5-4a62-a53f-2867dfa3b575.png)

### Expected Results

Things would be in color

### Actual Results

There is no color strip present

### Anything else?

N/A

**Comment by damianszczepanik** [comment]
Does not work with ``Red`` but you can do that successfully with format like ``#FF00FF``.

**Comment by luke-hill** [comment]
Correct, this contradicts the docs / information available. Please remedy when you have a chance.
