### ISSUE TITLE
Get replay url / ID for submitted teams message

### ISSUE THREAD

**Issue by szymon-owczarzak** [jenkinsci/office-365-connector-plugin#278]
### What feature do you want to see added?

First of all: thanks for developing this plugin - it's very useful to inform others about deployments 👍 

**I'm wondering would it be possible to get url / ID of a message posted on teams?**

### Scenario:
1. Jenkins Job **X** successfully built my app and sent artefacts to M2
2. Jenkins Job **X** triggered deployment Job **A** and **B** - does not wait for this to end
3. Jenkins Job **X** is sending Teams notification via `office365ConnectorSend` - `App build successful proceeding with deployments...`
#### Actual:
1. Job **A** and **B** will send next notifications after they finish (so we have 3 different notifications on a channel)
#### Expected:
1. Job **A** and **B** will replay to original notification after they finish (so we have only 1 notifications with 2 replies)

Maybe `office365ConnectorSend` could somehow return Message url or ID so it can be passed to Job **A** and **B**?

**Comment by damianszczepanik** [comment]
I don't think this is the correct way for solving this problem. You'd better try to make messages clear/unique so once you read it ins MS Teams you know what has triggered the message.

So customize the string of the message and don't try to hack ID or something like that which is IMO impossible
