### ISSUE TITLE
not show "View Build" on Teams

### ISSUE THREAD

**Issue by jiaming0708** [jenkinsci/office-365-connector-plugin#298]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.346.3
OS: Windows 10 - 10.0
---
Office-365-Connector:4.18.0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins server: windows 10

### Reproduction steps

My options in Jenkinsfile
```
    options {
        office365ConnectorWebhooks([
            [
                name: "Office 365",
                url: "{webhook url}",
                notifyBackToNormal: true,
                notifyFailure: true,
                notifyRepeatedFailure: true,
                notifySuccess: true,
                notifyAborted: true
            ]
        ])
    }
```

### Expected Results

have `View Build` button in the card, and link to jenkins website

### Actual Results

![image](https://user-images.githubusercontent.com/8855285/208839908-74897938-c6f6-47de-844a-170e12ada04b.png)

**Comment by damianszczepanik** [comment]
This looks like problem with rendering the button in Teams when no English language is used.

**Comment by jiaming0708** [comment]
Still without button when change to English
![image](https://user-images.githubusercontent.com/8855285/209489611-0e9ff567-7f1a-4d72-94e0-61c85d4b3a19.png)

There have button on error message.
![image](https://user-images.githubusercontent.com/8855285/209489600-168618cf-091e-49a9-b2cb-ec770b37425a.png)

**Comment by damianszczepanik** [comment]
Ouh, now it's clear - this is by design on some request https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/CardBuilder.java#L91 - if build succeed then there is no need to visit Jenkins for details so message is more compact

**Comment by jiaming0708** [comment]
got it!!
Follow the logic, there have any way to show the action button on success, could I file a PR for it?
