### ISSUE TITLE
Notification creates new conversation everytime

### ISSUE THREAD

**Issue by nair-sumesh** [jenkinsci/office-365-connector-plugin#300]
### Actual Behavior
The notifications from the same job creates a new conversation in MS Team channel.      

### Expectation
The plugin should check in the channel if a conversation from the same job exists     
- if NO, then create a new conversation (as it does today)
- If YES, then reply to the existing conversation

This will help grouping the notifications together for better UX and readability.

**Comment by LShelton** [comment]
I believe this is a limitation of the webbooks. Resolving this issue would significantly improve the quality of life. I'm not fond of the current behavior where the statuses 'Failed,' 'Continue Failing,' and 'Success' always generate a new thread. 

In my opinion, a more effective approach would be: 'If a job succeeds and then fails, create a new thread.' In this way, all relevant information (continue or success) would be contained within that thread, and a new thread would only be created when the job fails again. 

Presently, my Jenkins team messaging system is quite noisy when failures continue.

**Comment by damianszczepanik** [comment]
This is how webhooks work. Also I don't think this is convenient to have thousand of replies for first message.
