### ISSUE TITLE
Enhancement: Make the Build Number a link to the build URL

### ISSUE THREAD

**Issue by pharper-commscope** [jenkinsci/office-365-connector-plugin#320]
### What feature do you want to see added?

Messages sent include the following two lines at the top:

  Notification from <job-name>
  Latest status of build #<build-iteration-of-job>

I suggest that the '#<build-iteration-of-job>' be a link to the Jenkins page for that job iteration.

**Comment by damianszczepanik** [comment]
Link is already included https://github.com/jenkinsci/office-365-connector-plugin#with-jenkins-plugin
