### ISSUE TITLE
Documentation on Webhook Schema

### ISSUE THREAD

**Issue by justinmchase** [jenkinsci/office-365-connector-plugin#321]
### Describe your use-case which is not covered by existing documentation.

It would be really nice to have some documentation which fully describes the schema of the webhook this function is calling.

**Comment by damianszczepanik** [comment]
I believe https://github.com/jenkinsci/office-365-connector-plugin#examples is enough
For more details of the webhook you should probably check Office365 page

**Comment by justinmchase** [comment]
All of these examples seem to show the function api, but its not clear what payload is being sent to the webhook. It seems like this has two components two it, the part that runs in Jenkins and the Jenkins connector itself. I can't seem to find documentation on what payload is being sent to the connector.

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/office-365-connector-plugin/tree/master/src/test/resources/requests
