### ISSUE TITLE
office-365-connector-plugin looks for 200 code, power automate (workflow) gives a 202 causing it to fire three times

### ISSUE THREAD

**Issue by wjones38** [jenkinsci/office-365-connector-plugin#356]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins

### Reproduction steps

Change your office365ConnectorSend webhook url from a connector url to a working power automate url that targets a "When a Teams webhook request is received" trigger.

### Expected Results

The request should only be sent one time

### Actual Results

The request is sent three times

### Anything else?

I have gotten this plugin to work with the power automate system that Microsoft is pushing everyone over to with the only caveat being that it fires the HTTP request 3 times. Power automate returns a status of [SC_ACCEPTED](https://www.javadoc.io/static/org.apache.httpcomponents/httpcore/4.4.4/org/apache/http/HttpStatus.html#SC_ACCEPTED), not [SC_OK](https://www.javadoc.io/static/org.apache.httpcomponents/httpcore/4.4.4/org/apache/http/HttpStatus.html#SC_OK). Including all 200 codes as acceptable values for this plugin would greatly help its longevity.

**Comment by limuyuan** [comment]
Same issue here:
```
Started by user Admin
[Office365connector] Posting data to https://xxx.azure.com:443/workflows/xxx may have failed. Webhook responded with status code - 202
[Office365connector] Message from webhook - 
[Office365connector] Posting data to https://xxx.azure.com:443/workflows/xxx may have failed. Webhook responded with status code - 202
[Office365connector] Message from webhook - 
[Office365connector] Posting data to https://xxx.azure.com:443/workflows/xxx may have failed. Webhook responded with status code - 202
[Office365connector] Message from webhook - 
```
