### ISSUE TITLE
In Multibranch-Pipeline-Projects the jobname shown in the card is the name of the branch

### ISSUE THREAD

**Issue by vogelinho10** [jenkinsci/office-365-connector-plugin#50]
By using the Multibranch-Pipeline job-type the jobs for each branch is created automatically and the name of the branch is used as the job-name.
This job-name is then used by the connector-plugin in the cards.
Therefore we currently cannot see the name of the project in the cards.

![image](https://user-images.githubusercontent.com/31844598/34556022-0c544c98-f135-11e7-9b20-5084ec25bfa6.png)

**Comment by casz** [comment]
@vogelinho10 would #53 be the fix your looking for? :)

**Comment by vogelinho10** [comment]
yes
