### ISSUE TITLE
Proxy Exceptions Not Considered

### ISSUE THREAD

**Issue by jonnygrm** [jenkinsci/office-365-connector-plugin#56]
Hi,

We had to place a proxy exception on our network for *.office.com in order to get the Jenkins plugin to work.

What I realised was that the plugin does not seem to be picking up on the proxy exception rule I also set within Jenkins. I took a quick look at the plugin's source code and it looks as though it picks up the proxy settings but does not consider any exceptions, specifically, for anything related to office.com.

If I remove all proxy settings from Jenkins, the plugin does not use any proxy settings and in turn, gets past our proxy through a rule we added onto our proxy.

Thanks

Jonny

**Comment by damianszczepanik** [comment]
Any idea what could be wrong, how to fix it?

**Comment by damianszczepanik** [comment]
@jonnygrm I found some code about proxy which tells me that there is some configuration about this but maybe wrong 
https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/HttpWorker.java#L110

Are you still interesting this?

**Comment by damianszczepanik** [comment]
#202
