### ISSUE TITLE
any way to add an image to the notification card?

### ISSUE THREAD

**Issue by tony-kerz** [jenkinsci/office-365-connector-plugin#57]
tried adding the following to the `message` body, but neither worked:
```
<img src='http://memegenerator.net/img/instances/500x/49657864/yesss.jpg'/>
```
```
![yesss](http://memegenerator.net/img/instances/500x/49657864/yesss.jpg)
```
this [doc](https://jenkins.io/doc/pipeline/steps/Office-365-Connector/) says about the `message` arg:
> This is the main text in a message attachment, and can contain standard message markup

but i'm not clear on what "standard message markup" is in this context...?

**Comment by damianszczepanik** [comment]
You may find https://github.com/jenkinsci/office-365-connector-plugin/blob/master/README.md#documentation useful
