### ISSUE TITLE
threaded status possible?

### ISSUE THREAD

**Issue by douglasknudsen** [jenkinsci/office-365-connector-plugin#58]
I'd like to see if the connector can create a single message with subsequent statuses posted as replies.  So, new message for build 99 for STARTED, then reply with INPROGRESS, then reply with FAILED, etc...

**Comment by damianszczepanik** [comment]
Probably can if it will be implemented that way but there is no plan for that.

**Comment by zett42** [comment]
I would like to have this feature too. Typically our jobs post two message: 1. Build finished, 2. Tests finished. Showing all related messages in single thread would make the output much clearer, especially when there are many builds with interleaving statuses.
