### ISSUE TITLE
Use plugin for jobs defined in Jenkinsfile

### ISSUE THREAD

**Issue by moussetc** [jenkinsci/office-365-connector-plugin#59]
Hi!
Is it possible to use this interesting plugin for jobs that are defined by Jenkinsfile (not possible with the Jenkins website as shown in the Readme)? If yes, that might be a useful information to add to the Readme doc!

**Comment by casz** [comment]
@moussetc that's definitely possible, you can use the pipeline syntax snippet generator to help you with it.

https://jenkins.io/doc/book/pipeline/getting-started/#snippet-generator

**Comment by moussetc** [comment]
This is a part of Jenkins which I didn't know existed and it works very well, . Thank you very much for the fast answer!

**Comment by casz** [comment]
Good thing I linked to the entire getting started docs for pipeline :smile:

**Comment by moussetc** [comment]
That's what happens when the guy that setup the whole multipipeline build leaves and you get to take the reins :p

**Comment by casz** [comment]
Heh I did that last month 😀 however loving the switch :blush:
