### ISSUE TITLE
Pipeline console output - [Office365connector] No webhooks to notify

### ISSUE THREAD

**Issue by jmcu** [jenkinsci/office-365-connector-plugin#63]
For Office 365 Connector version 4.5, the following is logged in console output for all jobs (pass or fail), and could be confusing when people first see it while debugging build errors:

> [Office365connector] No webhooks to notify

It's in the log even if a webhookUrl value is set and working successfully in the Jenkinsfile.
`office365ConnectorSend message: "<Your message>", status:"<Build status>", webhookUrl:'<The connector webhook url>'`

**Comment by robventers4** [comment]
I can confirm the same behavior. Jobs with no webhook configured still provide the output twice: once at the start of the run, and once at the end.
`Started by user blah`
`[Office365connector] No webhooks to notify`
`Building in workspace /var/lib/jenkins/workspace/blah`
....
`[Office365connector] No webhooks to notify`
`Finished: SUCCESS`

It would be less confusing if there was no output when there are no webhooks configured.

**Comment by erenatas** [comment]
Can confirm this issue still exists.

**Comment by Gi0rgi0s** [comment]
I can confirm this as well

**Comment by derdour-r** [comment]
I can confirm this as well

**Comment by damianszczepanik** [comment]
Fixed in last release
