### ISSUE TITLE
pipeline syntax doesn't allow detailed configurations as in the manual job configuration

### ISSUE THREAD

**Issue by childnode** [jenkinsci/office-365-connector-plugin#64]
perhaps: it is not possible to suppress success notifications neither any timeouts ... or is this just an issue of "documentation" and the `/pipeline-syntax/` helper?

**Comment by damianszczepanik** [comment]
You can define macro for that purpose, check https://wiki.jenkins.io/display/JENKINS/Token+Macro+Plugin

**Comment by childnode** [comment]
hi @damianszczepanik , I'm sorry, but I don't see how this will help to workaround missing dataBindings in https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/workflow/Office365ConnectorSendStep.java !?

**Comment by damianszczepanik** [comment]
OK guys - what is your expectation?

**Comment by Bonifacio2** [comment]
Mine was satisfied, I just sent the links hoping they would be useful to somebody else.

**Comment by Digitalroot** [comment]
@Bonifacio2 Thank you. Here is the sample I used that worked for me. 
```
job('ci') {
    description 'Build and test the app.'
    configure { project ->
        project / 'properties' << 'jenkins.plugins.office365connector.WebhookJobProperty' {
            webhooks {
                'jenkins.plugins.office365connector.Webhook' {
                    name('MyName')
                    url('https://example.com')
                    startNotification(false)
                    notifySuccess(true)
                    notifyAborted(false)
                    notifyNotBuilt(false)
                    notifyUnstable(true)
                    notifyFailure(true)
                    notifyBackToNormal(true)
                    notifyRepeatedFailure(false)
                    timeout(30000)
                    macros(class: 'empty-list')
                }
            }
        }
    }
}
```

**Comment by damianszczepanik** [comment]
@Digitalroot would you like to update README file and add this sample as well?
