### ISSUE TITLE
Pipeline integration doesn't scale

### ISSUE THREAD

**Issue by childnode** [jenkinsci/office-365-connector-plugin#65]
Since 365 Connectors are set up per User in Outlook / Office 365, ou would need a hook per each user that wants to be notified

It would be much more useful to allow
1. declare outlook 365 notifications enabled with notification options
2. connector credentials are set up per jenkins user and automatically evaluated / used

=> no need to expand / change a pipeline not to make connectors public accessible for all users which might be used for harmful spamming

actually: this integration is by design not working for companies working with a 12factor app build and deploy

**Comment by casz** [comment]
Consider using Microsoft teams to notify instead of notifying a single user...

**Comment by childnode** [comment]
ohm, @casz you misunderstood my concern. It's not about "why is this connector set up per user only and I want to inform different people" at all but about the design principle of this connector that results in bad coded pipelines you can't ever re-use..
but hey ... I don't use it, just evaluated and want to give feedback. Feel free to dismiss this "issue"

**Comment by damianszczepanik** [comment]
We don't have plan for that
