### ISSUE TITLE
Webhook configuration at folder level

### ISSUE THREAD

**Issue by alexwhitman** [jenkinsci/office-365-connector-plugin#66]
We have a Jenkins instance with hundreds of jobs and it's impractical to have to configure each job to send a web hook.  It would be really good, if possible, to integrate with the Folders plugin (https://plugins.jenkins.io/cloudbees-folder) so that a web hook can be used for all jobs in that folder (recursively).

**Comment by casz** [comment]
If your using Jenkinsfile you can create a shared library step that sends notifications to teams and perhaps use some parameters. That's at least how we use it.

**Comment by thejimnicholson** [comment]
While you can send notifications using `office365ConnectorSend` from inside a pipeline/Jenkinsfile, there doesn't appear to be any way to suppress the `[Office365connector] No webhooks to notify` message for a pipeline job; at least this is true if you're using the Github Organizational Folders plugins. It would be best provide a pipeline mechanism for setting the values the connector requires, or at least suppress the calls to whatever the "default" notifiers are when the hook isn't set.

**Comment by damianszczepanik** [comment]
Don't have plan for this. I see that rules for this might be harder to implement and maintain then following above advice to have shared lib
