### ISSUE TITLE
Can we use regex for template values in advanced configuration?

### ISSUE THREAD

**Issue by themakshter** [jenkinsci/office-365-connector-plugin#67]
In the advanced configuration of this plugin, we can add multiple macros which have templates and we check their values. Is it possible to pass in a regex in the value section so that the template value matches a specific pattern?

Here is an example of what I want to do:

![image](https://user-images.githubusercontent.com/2033876/42385739-8e12f046-8135-11e8-9e73-dbb7bb76746f.png)

**Comment by damianszczepanik** [comment]
As described in help, you can use features offered by https://wiki.jenkins.io/display/JENKINS/Token+Macro+Plugin
