### ISSUE TITLE
Webhook responded with status code - 400

### ISSUE THREAD

**Issue by cashwu** [jenkinsci/office-365-connector-plugin#71]
Hi, I have got the status code 400 error, and it retries three times and success after 15 sec. May I know it could short the waiting time?
```
09:21:31 C:\Program Files (x86)\Jenkins\workspace\Test>exit 0 
09:21:31 [Office365connector] Posting data to "URL" may have failed. Webhook responded with status code - 400
09:21:31 [Office365connector] Message from webhook - Bad payload received by generic incoming webhook.
09:21:31 [Office365connector] Posting data to "URL" may have failed. Webhook responded with status code - 400
09:21:31 [Office365connector] Message from webhook - Bad payload received by generic incoming webhook.
09:21:32 [Office365connector] Posting data to "URL" may have failed. Webhook responded with status code - 400
09:21:32 [Office365connector] Message from webhook - Bad payload received by generic incoming webhook.
09:21:47 [Office365connector] Matched status 'SUCCESS' for webhook 'Test'.
09:21:47 Finished: SUCCESS
```
Even not webhook Url, it also success after 15 sec?
```
09:26:45 C:\Program Files (x86)\Jenkins\workspace\Test>exit 0 
09:27:01 [Office365connector] Matched status 'SUCCESS' for webhook 'null'.
09:27:01 Finished: SUCCESS
```

**Comment by cashwu** [comment]
I find the is Jenkins issue

**Comment by dremur** [comment]
Hey cashwu, what did you find the issue to be because I'm having the same problem.

**Comment by cashwu** [comment]
Hi @dremur, I try to find out the issue and not get really root cause now, but It is not office-365-connector plugin issue I think, I had uninstalled the plugin but has the same issue.

**Comment by Ewynne** [comment]
Hey @dremur we started seeing this issue with our jenkins builds today, with intermittent success. Was there some Jenkins issue with the solution to the problem that you could link here?

**Comment by tfarmer00** [comment]
This appears to still be an issue with the latest version of the plugin.
