### ISSUE TITLE
Additional text on card?

### ISSUE THREAD

**Issue by jimpriest** [jenkinsci/office-365-connector-plugin#76]
Could the name that is defined in the webhook config be passed into the message?  

It appears the 'title' text used in Teams is pulled from the test name/displayname.

What happens is my Jenkins display name is defined and I cannot change it - so that's gets sent into Teams - but I'd like to add some additional info into the message to better identify where the message was coming from...

So...
Update from  DISPLAY NAME IN JENKINS
latest status of build #123
Some additional info passed in via Jenkinsfile for default webhook 

```
office365ConnectorWebhooks([[
        name: 'Some additional info passed in via Jenkinsfile for default webhook ',
        url: 'https://foobar'
    ]]),
```

**Comment by damianszczepanik** [comment]
Should be covered by https://github.com/jenkinsci/office-365-connector-plugin/pull/140
