### ISSUE TITLE
Uploading files. (feature request) 

### ISSUE THREAD

**Issue by ZeerDonker** [jenkinsci/office-365-connector-plugin#78]
Hi,

Can office365 webhooks be used to upload files? 
If yes, can this functionality be build into this plugin?

Slack jenkins example: 
https://github.com/jenkinsci/slack-uploader-plugin
(It uses curl together with slacks api, with the bot plugin & token in Slack, to upload files in a folder. )

**Comment by damianszczepanik** [comment]
No plan for this
