### ISSUE TITLE
Show default jobname _and_ display name on card

### ISSUE THREAD

**Issue by hurzelchen** [jenkinsci/office-365-connector-plugin#79]
This is addition to issue #50.
When having a multibranch project, the default jobname looks something like "Project Name >> branch". We additionally set the display name to our combined build number "#12345" using build-name-setter.

Usually, Jenkins will show both information next to each other (e.g. in the executor status widget, in the job overview, in the breadcrumbs for build).

But the card will either say "Update from Project Name >> branch" if the display name is empty or "Update from #12345" otherwise. Would it be possible to have it (maybe configurable) say "Update from Project Name >> branch #12345".

Yes, I could put all that info into the display name, but if that gets too long it will break the layout on Jenkins' web page.

**Comment by hurzelchen** [comment]
I think #80 might be an even nicer way.

**Comment by damianszczepanik** [comment]
@hurzelchen closing this as I believe this is not valid any more. If not, let me know
