### ISSUE TITLE
Build failure compiling latest

### ISSUE THREAD

**Issue by tfarmer00** [jenkinsci/office-365-connector-plugin#83]
[INFO] Done FindBugs Analysis....
[INFO]
[INFO] <<< findbugs-maven-plugin:3.0.5:check (findbugs) < :findbugs @ Office-365-Connector <<<
[INFO]
[INFO]
[INFO] --- findbugs-maven-plugin:3.0.5:check (findbugs) @ Office-365-Connector ---
[INFO] BugInstance size is 2
[INFO] Error size is 0
[INFO] Total bugs: 2
[INFO] Null passed for non-null parameter of hudson.model.Run.getEnvironment(TaskListener) in jenkins.plugins.office365connector.FactsBuilder.getTagNumber() [jenkins.plugins.office365connector.FactsBuilder] At FactsBuilder.java:[line 134] NP_NONNULL_PARAM_VIOLATION
[INFO] Dead store to authors in jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier.addScmDetails(boolean) [jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier] At Office365ConnectorWebhookNotifier.java:[line 347] DLS_DEAD_LOCAL_STORE
[INFO]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:34 min
[INFO] Finished at: 2019-01-08T17:36:23-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:check (findbugs) on project Office-365-Connector: failed with 2 bugs and 0 errors-> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by damianszczepanik** [comment]
Should not happen with recent releases.
