### ISSUE TITLE
OSS License

### ISSUE THREAD

**Issue by tylersmith34** [jenkinsci/office-365-connector-plugin#87]
What is the open source license associated with this plugin?  My company requires this information when evaluating any plugin and your repo doesn't list one.

**Comment by casz** [comment]
It is right in the POM.xml
https://github.com/jenkinsci/office-365-connector-plugin/blob/ba4144184a3233bf29d6fc438957d22bc6fe67fa/pom.xml#L9-L16

**Comment by tylersmith34** [comment]
Can you add a license file so it can be viewed by non engineers at a glance? Many engineers like myself send open source red tape police to repos to see the license so they'll approve using that code and they won't know how to dig in Maven files.  Github can display a license.md file as part of the UI.

**Comment by casz** [comment]
@tylersmith34 open a PR?

**Comment by tylersmith34** [comment]
Sure, you'll probably see it next week.

**Comment by tylersmith34** [comment]
@casz I opened a PR with the license file.
