### ISSUE TITLE
Jenkins connector is not available in Microsoft Teams

### ISSUE THREAD

**Issue by kbudde** [jenkinsci/office-365-connector-plugin#89]
Hi,

I've integrated successful the plugin in one outlook 365 group.

We want to integrate the notifications in a MS Teams channel.
Unfortunately, if I try to add a connector in Microsoft Teams the jenkins connector is not found. 

Should it be there? Microsoft is currently doing a lot of changes for Teams. Perhaps the connector has to be submitted again/updated.

**Comment by kbudde** [comment]
Hi, 
it is not related to the plugin. 
Regarding the microsoft support it could be related to an update for Microsoft Teams.

You have to enable: "Allow external apps in Microsoft Teams" and "Allow sideloading of external apps" in office365 admin > Settings > Service & add-ins > Microsoft Teams > Apps

**Comment by saikrishna86** [comment]
I am unable to see jenkins in teams connector, can we have any solution
