### ISSUE TITLE
Configure Plugin via Jenkinsfile

### ISSUE THREAD

**Issue by rhnewtron** [jenkinsci/office-365-connector-plugin#90]
We would like to the use plugin and want to configure it (webhook URL, when to post etc) on the Job Level via Jenkinsfile. We want to do "Everything is code" and it seems that is not possible to use the default integration that can be configured in the GUI after the job has been created from a Jenkinsfile. We always have to go back to 

```
office365ConnectorSend color: 'Red', message: 'Hello', status: 'FAILED', webhookUrl: 'https://test'
```
Which is very unconvenient. Would be great to configure the plugin in the Jenkinsfile.

**Comment by casz** [comment]
@rhnewtron look under the job properties. The plugin is fully configurable there.

The pipeline syntax generator should be able to help you.

**Comment by rhnewtron** [comment]
Thanks for the Tip. For Scripted Pipeline it is rather easy:
```
properties(
  [
    office365ConnectorWebhooks([[notifyBackToNormal: true, notifyFailure: true, notifyRepeatedFailure: true, notifySuccess: true, notifyUnstable: true, url: 'https://your_webhook_url_here']])
  ]
)
```
I think we can close this issue. Maybe update the documentation with some hints.

**Comment by casz** [comment]
This is the same for declarative pipeline :)

**Comment by damianszczepanik** [comment]
I'm using `post` section

https://jenkins.io/doc/book/pipeline/syntax/#post

**Comment by andreatondelli** [comment]
> 
> This is the same for declarative pipeline :)

Can you post a complete example of declarative pipeline?
I'm trying to configure it on **Jenkinsfile** for **multibranch pipeline** project and office365ConnectorSend work while office365ConnectorWebhooks don't.

```
pipeline {
    agent any 
    stages {
        /* ... */
    }
    post {
       always {
        office365ConnectorSend color: 'Green', message: 'Success', status: 'SUCCESS', webhookUrl:'https://outlook.office.com/webhook/xxxxxxxxxxxx'
       }
    }
}
```
Using office365ConnectorWebhooks ?
```
pipeline {
    agent any 
    stages {
        /* ... */
    }
    post {
       always {
           /* ???????????? */
       }
    }
}
```

Obviously I will use all the conditions in post (always, changed, fixed...)


Thanks in advance!
Andrea

**Comment by fipsingdale** [comment]
> @andreatondelli You can do the following:
> 
> ```
> options {
>   office365ConnectorWebhooks([
>     [name: "Office 365", url: "https://outlook.office.com/webhook/xxxxxxxxxxxx", notifyFailure: true]
>   ])
> }
> ```
> 
> Discovered this using the **Declarative Directive Generator**...

it seems to be crucial to configure name for the connector - otherwise it will not work!

**Comment by damianszczepanik** [comment]
Guys, I'm happy to accept PR if you think README should be improved

**Comment by rounak-codiant** [comment]
What if I don't want to hardcode the URL in jenkinsfile. As Jenkinsfile will be on git and URL should be passed via variable or credentials for security purposes.

**Comment by damianszczepanik** [comment]
Try https://github.com/jenkinsci/office-365-connector-plugin#jenkins-global-configuration
